### PR TITLE
Merging v2.5.x on main

### PR DESCRIPTION
**Pull request by Halbaroth**

### CODE REVIEW

**Comment by bclement-ocp** [comment]
Looks like there are conflicts here :( Should we revert the few commits for 2.3.3 that seems to be on `main` but not `next`?

**Comment by Halbaroth** [comment]
We shouldn't remove the commit e0b89ab53a39fdd56c80ed075dc043dcf767f6b7 on main as the tag of the release `2.3.3` is on this commit. It seems a release has been done by pushing a branch to `master` (renamed `main` later) and the branch have never been pushed on `next`.

**Comment by bclement-ocp** [comment]
Sorry, I meant revert the commits (as in `git revert`), not remove them.

**Comment by Halbaroth** [comment]
Merging `v2.5.x` on `main` isn't a good idea as `main` is supposed to be a prefix of `next` and `v2.5.x` diverged from `next`.

**Pull request closed without merging**
