### PR TITLE
Mutually recursive definitions for Dolmen frontend

### PR DESCRIPTION
**Pull request by Halbaroth**
This PR add the support for mutually recursive definitions of functions and predicates through Dolmen.

We can define mutually functions as follow:
`function ... and function ... `
and mutually predicates
`predicate ... and predicate ... `

~~If you want to  mix both, you have to define your predicates as functions returning the type `Prop`.~~

This shouldn't be merge before the next release of Dolmen.

### CODE REVIEW

**Comment by hra687261** [comment]
With the native front-end it's possible to mix predicates and functions, this one should have the same behavior IMO.

**Comment by Halbaroth** [comment]
Ok, I will fix it.

**Review by hra687261 — CHANGES_REQUESTED** [review]
[Dolmen 0.8.1](https://opam.ocaml.org/packages/dolmen/dolmen.0.8.1/) has been released, adding it as a constraint to `dune-project` should fix the CI and you probably don't need to pin it to the github repo.

**Review by hra687261 — CHANGES_REQUESTED** [review]
I noticed that the file [tests/typing/mutual-recursion001.ae](https://github.com/OCamlPro/alt-ergo/pull/550/files#diff-9a505ddff945ee889e6a2f0f3cd24949b480228b9921f66d2c36c60a6e362a54) has been deleted, can you add it back since it shows the mixing of both predicate and function definitions?
Since Gbury/dolmen#129 has been merged it should be possible to do that with dolmen now.

Edit: I was going to mention the missing predicate attribute issue, but apparently it was already noticed Gbury/dolmen#130

**Comment by Halbaroth** [comment]
The release 0.8.1 will not fix the issue with predicate tag solved in https://github.com/Gbury/dolmen/pull/130. Besides, there are some little things to fix in the Alt-Ergo parser of Dolmen. I prefer pinning the dev version to have a working CI than waiting for the next release of Dolmen.

**Review by hra687261 — APPROVED** [review]

**Comment by hra687261** [comment]
Ok, depending on the amount of changes that will need to be done on Dolmen, maybe @Gbury can patch the 0.8.1 release?

**Comment by Halbaroth** [comment]
@Gbury  will release another minor version soon. I will merge this PR as soon as the CI passes.

**Comment by hra687261** [comment]
Fine by me, you can probably merge #545 too after this one.

**Comment by Halbaroth** [comment]
> I noticed that the file [tests/typing/mutual-recursion001.ae](https://github.com/OCamlPro/alt-ergo/pull/550/files#diff-9a505ddff945ee889e6a2f0f3cd24949b480228b9921f66d2c36c60a6e362a54) has been deleted, can you add it back since it shows the mixing of both predicate and function definitions? Since [Gbury/dolmen#129](https://github.com/Gbury/dolmen/pull/129) has been merged it should be possible to do that with dolmen now.
> 

I didn't remove it but rename it actually ;)

**Comment by hra687261** [comment]
Renamed and changed! Because the two test files didn't mix mutually recursive predicate and function definitions.

**Pull request merged**
