### PR TITLE
Remove useless `id` arg from multiple expr.ml funs

### PR DESCRIPTION
**Pull request by hra687261**

### CODE REVIEW

**Comment by bclement-ocp** [comment]
I believe @Halbaroth explained to me once that these were used by the GUI, but this PR doesn't look like it touches the GUI. Was it incorrect, or did you leave some entry points for the GUI?

If so, we should remove them as well once #601 is merged.

**Comment by Halbaroth** [comment]
I have a PR that does exactly the same thing. I don't publish it yet because I am waiting the review for the GUI PR :)

**Comment by hra687261** [comment]
> I believe @Halbaroth explained to me once that these were used by the GUI, but this PR doesn't look like it touches the GUI. Was it incorrect, or did you leave some entry points for the GUI?

I'm pretty sure the GUI builds a typed AST which is then translated to exprs and all the entry-points are from `cnf.ml`, `d_cnf.ml` and a couple other "backend" modules. So unless it's done indirectly somehow, I'm not seeing it.

> I have a PR that does exactly the same thing. I don't publish it yet because I am waiting the review for the GUI PR :)

We can close this PR if that is the case.
Do you mind explaining how the GUI uses these ids?

**Comment by hra687261** [comment]
Well since the GUI was removed, I guess this one can be merged then?

**Comment by bclement-ocp** [comment]
should we remove the `id` parameter of `mk_form` as well?

**Comment by bclement-ocp** [comment]
Also can we remove the `Expr.id` function now that it is meaningless?

**Comment by hra687261** [comment]
Will do!

**Comment by hra687261** [comment]
Done!

**Review by bclement-ocp — APPROVED** [review]
:+1:

**Pull request merged**
