### PR TITLE
Removing flattening that causes regression

### PR DESCRIPTION
**Pull request by Stevendeo**
Attempt to solve #505

### CODE REVIEW

**Review by Gbury — COMMENTED** [review]
Seems correct, but I'd prefer if we could benchmark this before merging.

**Comment by Stevendeo** [comment]
Tests on this simple fix lead to a lot of regressions. I will investigate the cause of the regression, maybe matching addition terms with a different number of arguments is one of the issues here.

**Comment by Halbaroth** [comment]
What is the status of this PR? We should fix this bug for the release 2.4.3.

**Comment by Halbaroth** [comment]
I will fix this bug for the release 2.4.3. See https://github.com/OCamlPro/alt-ergo/pull/546

**Pull request closed without merging**
