### PR TITLE
Result conflict and ppxlib

### PR DESCRIPTION
**Pull request by Halbaroth**
We have to use ppxlib >= 0.30.0 and prevent conflict with result < 1.5.

### CODE REVIEW

**Comment by bclement-ocp** [comment]
We shouldn't have a dependency on `result` at all, we don't use it. I thought we solved this by adding a version restriction on `fmt` instead; do we have other dependencies that bring in `result`?

We also don't use `ppxlib`, so we shouldn't have it as a dependency either. What is broken?

**Comment by Halbaroth** [comment]
`ppxlib` is used by recent `ppx_blob`. We have to use recent `ppx_blob` as older versions are not compatible with `Dune > 3`. If we don't use a recent version of `ppxlib`, it doesn't recognize user-defined binding operators: 
https://v2.ocaml.org/manual/bindingops.html 
I guess the AST of OCaml is not correct into too old `ppxlib` libraries.

I will check for the result dependency.

EDIT:  if you prefer, I can add `ppx_lib < 0.30.0` as a conflict clause instead of a dependency. It makes more sense.

**Comment by bclement-ocp** [comment]
> `ppxlib` is used by recent `ppx_blob`. We have to use recent `ppx_blob` as older versions are not compatible with `Dune > 3`. If we don't use a recent version of `ppxlib`, it doesn't recognize user-defined binding operators:

Ah, so `ppx_blob` is the one that probably doesn't have proper dependency constraints, OK. Adding a conflicts clause on old ppxlib (with a comment that it's for `ppx_blob`) makes more sense then, good idea!

**Comment by bclement-ocp** [comment]
I think `result` is `logs` through `ocplib-simplex`, OK for that then :'(

**Review by bclement-ocp — APPROVED** [review]
Let's merge this as is then, since #815 was merged already it will make things easier for us. We can clean up the `ppxlib` dependency into a `conflicts` once we are done with 2.5.0

**Pull request merged**
