### PR TITLE
feat: Statically linked binary releases

### PR DESCRIPTION
**Pull request by bclement-ocp**
This patch modifies the Docker workflow to build a statically linked portable binary of Alt-Ergo, following [1].

Building the Linux binaries is fairly quick and hence performed on push/pull_request.

[1] : https://ocamlpro.com/blog/2021_09_02_generating_static_and_portable_executables_with_ocaml/

### CODE REVIEW

**Comment by bclement-ocp** [comment]
(Marking as draft because the macOS binaries do not work)

**Comment by bclement-ocp** [comment]
Updated to only include static builds for Linux/x86_64 for now, and to build with flambda enabled.

**Comment by bclement-ocp** [comment]
Statically linked x86-64 linux binaries for this PR are [here](https://github.com/OCamlPro/alt-ergo/actions/runs/8360536142?pr=1045)

**Comment by bclement-ocp** [comment]
I got access to a macOS machine internally and could debug the macOS build; this is not enabled by default (needs a manual workflow trigger) but is included in this PR now. It was tested separately (see #1067 ).

This should actually be ready for review now :)

**Review by Halbaroth — APPROVED** [review]

**Pull request merged**
