### PR TITLE
CI fix for dune-build-info

### PR DESCRIPTION
**Pull request by bclement-ocp**

### CODE REVIEW

**Comment by bclement-ocp** [comment]
Note: this should be OK to backport for 2.4.3

**Comment by Halbaroth** [comment]
Seems fine but still I prefer putting all the tests in the directory `tests/`. Could create subdirectories in it and modify `gentest.ml` accordingly?

**Comment by bclement-ocp** [comment]
Forgot about that — done.

**Review by Halbaroth — APPROVED** [review]
Thanks :)

**Pull request merged**
