### PR TITLE
Release 2.6.0

### PR DESCRIPTION
**Pull request by Halbaroth**
We are ready to start the release process for `2.6.0`!

### CODE REVIEW

**Comment by bclement-ocp** [comment]
Please rebase after #1219. Should we wait a bit at least on the documentation changes you mentioned in #1134 before doing this to avoid churn with duplicate PRs? It is not like there is going to be development on the `next` branch this week that is not related to the release.

**Comment by Halbaroth** [comment]
Sure, I plan to rebase after merging documentation.

**Comment by Halbaroth** [comment]
I think we are ready to start the release process @bclement-ocp

**Review by bclement-ocp — APPROVED** [review]
I think Try Alt-Ergo is currently broken but I don't think that should block the release.

**Comment by bclement-ocp** [comment]
> I think Try Alt-Ergo is currently broken but I don't think that should block the release.

More precisely `worker_js.ml` does not seem to be compatible with dolmen.

**Comment by Halbaroth** [comment]
The worker is not a part of the release. We can fix it after publishing 2.6.0.

**Pull request merged**
