### PR TITLE
Transforming all ite conditions into terms

### PR DESCRIPTION
**Pull request by Stevendeo**
Fixes issue #519

### CODE REVIEW

**Review by Gbury — DISMISSED** [review]

**Comment by Halbaroth** [comment]
Should we test this PR on Marvin also?

**Comment by Gbury** [comment]
> Should we test this PR on Marvin also?

yup

**Comment by Stevendeo** [comment]
@Gbury @Halbaroth A lot of changes since the previous version; the type `term_view` has fully changed. I am also considering changing  types `lit_view` and `form_view` to remove `Not_a_*` cases.

**Comment by Halbaroth** [comment]
This PR is not the same anymore. Should I dismiss the Guillaume's review?

**Review by Halbaroth — APPROVED** [review]
Fair enough ;)

**Pull request merged**
