### PR TITLE
Propagate equalities within int2bv

### PR DESCRIPTION
**Pull request by bclement-ocp**
This patch adds some reasoning support in bitv_rel for equalities and disequalities between `int2bv` terms. More specifically, when an equality or disequality (~ stands for either `=` or `distinct`):

  `(~ ((_ int2bv n) t) ((_ int2bv n) u))`

is asserted, we also assert that `t` and `u` are congruent (resp. noncongruence) modulo `2^n`, i.e.

  `(~ (mod (- t u) (pow 2 n)) 0)`

This allows recovering some reasoning power involving bitvector terms containing `int2bv`, and in particular terms involving bitvector arithmetic (since bitvector arithmetic is currently implemented using `int2bv`).

### CODE REVIEW

**Comment by bclement-ocp** [comment]
Draft because I need to re-run benches on this.

**Comment by bclement-ocp** [comment]
This is +40-0 on smtlib22/QF_BV. Not sure I want to nominate this for 2.5.0, it's nice to have but not necessary so we can postpone (but I had it laying around so might as well make the PR).

**Comment by Halbaroth** [comment]
Let's postpone it.

**Comment by bclement-ocp** [comment]
Following my investigations for #474 and #801 I have a better understanding of the type of equalities we see in relations, and in its current instantiation, this is not a general solution and will only propagate `int2bv` equalities in very specific situations. An implementation that correctly propagates `int2bv` equalities in the general case will be more involved and requires additional work, closing for now and opening an issue instead.

**Pull request closed without merging**
